  name: Generate Snake

  on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * *"

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Generate Snake SVG (direct to root)
          uses: Platane/snk@v3
          with:
            github_user_name: ${{ github.repository_owner }}
            outputs: |
              github-contribution-grid-snake.svg
              github-contribution-grid-snake-dark.svg?palette=github-dark

        - name: Configure git
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        - name: Commit and push to output branch
          run: |
            git switch -c output || git switch output
            git reset --hard main
            git add github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg
            git commit -m "Update snake SVGs [skip ci]" || echo "No changes"
            git push origin output --force
